### ISSUE TITLE
Fails to Compile

### ISSUE THREAD

**Issue by genifycom** [chrissainty/BlazorToast#1]
With Visual Studio 2019 Preview Version 16.2.0 Preview 3.0 and DotNet v3.0.0-preview 6

This fails to compile with 

1>------ Rebuild All started: Project: BlazorToastNotifications, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>C:\...\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code 1.
1>Done building project "BlazorToastNotifications.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by chrissainty** [comment]
Apologies for not getting to this sooner. The code was written quite a while a go and has not been updated to the latest preview, hence why you're struggling to build it. 

I'm going through and updating as many of my older blog posts and code samples as I can and have just push an update to this repo to make to preview 6 compatible. You should be able to build it now.
